"""
Class which matches the patent subclass to their description
"""
class IPC_Patent:
    patents = {
        "A01": "AGRICULTURE; FORESTRY; ANIMAL HUSBANDRY; HUNTING; TRAPPING; FISHING",
        "A01B": "Soil working in agriculture or forestry; Parts; details; or accessories of agricultural machines or implements; in general",
        "A01C": "Planting; Sowing; Fertilising",
        "A01D": "Harvesting; Mowing",
        "A01F": "Processing of harvested produce; Hay or straw presses; Devices for storing agricultural or horticultural produce",
        "A01G": "Horticulture; Cultivation of vegetables; flowers; rice; fruit; vines; hops; or seaweed; Forestry; Watering",
        "A01H": "New plants or processes for obtaining them; Plant reproduction by tissue culture techniques",
        "A01J": "Manufacture of dairy products",
        "A01K": "Animal husbandry; Care of birds; fishes; insects; Fishing; Rearing or breeding animals; not otherwise provided for; New breeds of animals",
        "A01L": "Shoeing of animals",
        "A01M": "Catching; trapping or scaring of animals; Apparatus for the destruction of noxious animals or noxious plants",
        "A01N": "Preservation of bodies of humans or animals or plants or parts thereof; Biocides; e.g. as disinfectants; as pesticides; as herbicides; Pest repellants or attractants; Plant growth regulators",
        "A21":  "BAKING; EDIBLE DOUGHS",
        "A21B": "Bakers' ovens; Machines or equipment for baking",
        "A21C": "Machines or equipment for making or processing doughs; Handling baked articles made from dough",
        "A21D": "Treatment; e.g. preservation; of flour or dough; e.g. by addition of materials; Baking; Bakery products; Preservation thereof",
        "A22":  "BUTCHERING; MEAT TREATMENT; PROCESSING POULTRY OR FISH",
        "A22B": "Slaughtering",
        "A22C": "Processing meat; poultry; or fish",
        "A23": "FOODS OR FOODSTUFFS; THEIR TREATMENT; NOT COVERED BY OTHER CLASSES",
        "A23B": "Preserving; e.g. by canning; meat; fish; eggs; fruit; vegetables; edible seeds; Chemical ripening of fruit or vegetables; The preserved; ripened; or canned products",
        "A23C": "Dairy products; e.g. milk; butter; cheese; Milk or cheese substitutes; Making thereof",
        "A23D": "Edible oils or fats; e.g. margarines; shortenings; cooking oils",
        "A23F": "Coffee; Tea; Their substitutes; Manufacture; preparation; or infusion thereof",
        "A23G": "Cocoa; Chocolate; Confectionery; Ice-cream",
        "A23J": "Protein compositions for foodstuffs; Working-up proteins for foodstuffs; Phosphatide compositions for foodstuffs",
        "A23K": "Fodder",
        "A23L": "Foods; foodstuffs; or non-alcoholic beverages; not covered by subclasses A 23 B to J; Their preparation or treatment; e.g. cooking; modification of nutritive qualities; physical treatment; Preservation of foods or foodstuffs; in general",
        "A23N": "Machines or apparatus for treating harvested fruit; vegetables; or flower bulbs in bulk; not otherwise provided for; Peeling vegetables or fruit in bulk; Apparatus for preparing animal feeding-stuffs",
        "A23P": "Shaping or working of foodstuffs; not fully covered by a single other subclass",
        "A24":  "TOBACCO; CIGARS; CIGARETTES; SMOKERS'REQUISITES",
        "A24B": "Manufacture or preparation of tobacco for smoking or chewing; Tobacco; Snuff",
        "A24C": "Machines for making cigars or cigarettes",
        "A24D": "Cigars; Cigarettes; Tobacco smoke filters; Mouthpieces for cigars or cigarettes; Manufacture of tobacco smoke filters or mouthpieces",
        "A24F": "Smokers' requisites; Match boxes",
        "A41": "WEARINGAPPAREL",
        "A41B": "Shirts; Underwear; Baby linen; Handkerchiefs",
        "A41C": "Corsets; Brassières",
        "A41D": "Outerwear; Protective garments; Accessories",
        "A41F": "Garment fastenings; Suspenders",
        "A41G": "Artificial flowers; Wigs; Masks; Feathers",
        "A41H": "Appliances or methods for making clothes; e.g. for dress-making; for tailoring; not otherwise provided for",
        "A42":  "HEADWEAR",
        "A42B": "Hats; Head coverings",
        "A42C": "Manufacturing or trimming hats or other head coverings",
        "A43":  "FOOTWEAR",
        "A43B": "Characteristic features of footwear; Parts of footwear",
        "A43C": "Fastenings or attachments for footwear; Laces in general",
        "A43D": "Machines; tools; equipment or methods for manufacturing or repairing footwear",
        "A44":  "HABERDASHERY; JEWELLERY",
        "A44B": "Buttons; pins; buckles; slide fasteners; or the like",
        "A44C": "Jewellery; Bracelets; Other personal adornments; Coins",
        "A45":  "HAND OR TRAVELLINGARTICLES",
        "A45B": "Walking sticks; Umbrellas; Ladies' or like fans",
        "A45C": "Purses; Travelling bags or baskets; Suitcases",
        "A45D": "Hairdressing or shaving equipment; Manicuring or other cosmetic treatment",
        "A45F": "Travelling or camp equipment",
        "A46": "BRUSHWARE",
        "A46B": "Brushes",
        "A46D": "Manufacture of brushes",
        "A47": "FURNITURE; DOMESTIC ARTICLES OR APPLIANCES; COFFEE MILLS; SPICE MILLS; SUCTION CLEANERS IN GENERAL",
        "A47B": "Tables; Desks; Office furniture; Cabinets; Drawers; General details of furniture",
        "A47C": "Chairs; Sofas; Beds",
        "A47D": "Furniture specially adapted for children",
        "A47F": "Special furniture; fittings; or accessories for shops; storehouses; bars; restaurants; or the like; Paying counters",
        "A47G": "Household or table equipment",
        "A47H": "Furnishings for windows or doors",
        "A47J": "Kitchen equipment; Coffee mills; Spice mills; Apparatus for making beverages",
        "A47K": "Sanitary equipment not otherwise provided for; Toilet accessories",
        "A47L": "Domestic washing or cleaning; Suction cleaners in general",
        "A61": "MEDICAL OR VETERINARY SCIENCE; HYGIENE",
        "A61B": "Diagnosis; Surgery; Identification",
        "A61C": "Dentistry; Oral or dental hygiene",
        "A61D": "Veterinary instruments; implements; tools; or methods",
        "A61F": "Filters implantable into blood vessels; Prostheses; Orthopaedic; nursing or contraceptive devices; Fomentation; Treatment or protection of eyes or ears; Bandages; dressings or absorbent pads; Firstaid kits",
        "A61G": "Transport or accommodation for patients; Operating tables or chairs; Chairs for dentistry; Funereal devices",
        "A61H": "Physical therapy apparatus; e.g. devices for locating or stimulating reflex points in the body; Artificial respiration; Massage; Bathing devices for special therapeutic or hygienic purposes or specific parts of the body",
        "A61J": "Containers specially adapted for medical or pharmaceutical purposes; Devices or methods specially adapted for bringing pharmaceutical products into particular physical or administering forms; Devices for administering food or medicines orally; Baby comforters; Devices for receiving spittle",
        "A61K": "Preparations for medical; dental; or toilet purposes",
        "A61L": "Methods or apparatus for sterilising materials or objects in general; Disinfection; sterilisation; or deodorisation of air; Chemical aspects of bandages; dressings; absorbent pads; or surgical articles; Materials for bandages; dressings; absorbent pads; or surgical articles",
        "A61M": "Devices for introducing media into; or onto; the body; Devices for transducing body media or for taking media from the body; Devices for producing or ending sleep or stupor",
        "A61N": "Electrotherapy; Magnetotherapy; Radiation therapy; Ultrasound therapy",
        "A61P": "Therapeutic activity of chemical compounds or medicinal preparations",
        "A62": "LIFE-SAVING; FIRE-FIGHTING",
        "A62B": "Devices; apparatus; or methods for life-saving",
        "A62C": "Fire-fighting",
        "A62D": "Chemical means for extinguishing fires or for combating or protecting against harmful chemical agents; Chemical materials for use in breathing apparatus",
        "A63": "SPORTS; GAMES; AMUSEMENTS",
        "A63B": "Apparatus for physical training; gymnastics; swimming; climbing; or fencing; Ball games; Training equipment",
        "A63C": "Skates; Skis; Roller skates; Design or layout of courts; rinks or the like",
        "A63D": "Bowling-alleys; Bowling games; Boccia; Bowls; Bagatelle; Billiards",
        "A63F": "Card; board; or roulette games; Indoor games using small moving playing bodies; Miscellaneous games",
        "A63G": "Merry-go-rounds; Swings; Rocking-horses; Chutes; Switchbacks; Similar devices for public amusement",
        "A63H": "Toys; e.g. tops; dolls; hoops; building blocks",
        "A63J": "Devices for theatres; circuses; or the like; Conjuring appliances or the like",
        "A63K": "Racing; Riding sports; Equipment or accessories therefor",
        "B01": "PHYSICAL OR CHEMICAL PROCESSES OR APPARATUS IN GENERAL",
        "B01B": "Boiling; Boiling apparatus",
        "B01D": "Separation",
        "B01F": "Mixing; e.g. dissolving; emulsifying; dispersing",
        "B01J": "Chemical or physical processes; e.g. catalysis; colloid chemistry; Their relevant apparatus",
        "B01L": "Chemical or physical laboratory apparatus for general use",
        "B02": "CRUSHING; PULVERISING; OR DISINTEGRATING; PREPARATORY TREATMENT OF GRAIN FOR MILLING",
        "B02B": "Preparing grain for milling; Refining granular fruit to commercial products by working the surface",
        "B02C": "Crushing; pulverising; or disintegrating in general; Milling grain",
        "B03": "SEPARATION OF SOLID MATERIALS USING LIQUIDS OR USING PNEUMATIC TABLES OR JIGS; MAGNETIC OR ELECTROSTATIC SEPARATION OF SOLID MATERIALS FROM SOLID MATERIALS OR FLUIDS; SEPARATION BY HIGHVOLTAGE ELECTRIC FIELDS",
        "B03B": "Separating solid materials using liquids or using pneumatic tables or jigs",
        "B03C": "Magnetic or electrostatic separation of solid materials from solid materials or fluids; Separation by high-voltage electric fields",
        "B03D": "Flotation; Differential sedimentation",
        "B04": "CENTRIFUGALAPPARATUS OR MACHINES FOR CARRYING-OUT PHYSICAL OR CHEMICAL PROCESSES",
        "B04B": "Centrifuges",
        "B04C": "Apparatus using free vortex flow; e.g. cyclones",
        "B05": "SPRAYING OR ATOMISING IN GENERAL; APPLYING LIQUIDS OR OTHER FLUENT MATERIALS TO SURFACES; IN GENERAL",
        "B05B": "Spraying apparatus; Atomising apparatus; Nozzles",
        "B05C": "Apparatus for applying liquids or other fluent materials to surfaces; in general",
        "B05D": "Processes for applying liquids or other fluent materials to surfaces; in general",
        "B06": "GENERATING OR TRANSMITTING MECHANICAL VIBRATIONS IN GENERAL",
        "B06B": "Generating or transmitting mechanical vibrations in general",
        "B07": "SEPARATING SOLIDS FROM SOLIDS; SORTING",
        "B07B": "Separating solids from solids by sieving; screening; or sifting or by using gas currents; Other separating by dry methods applicable to bulk material; e.g. loose articles fit to be handled like bulk material",
        "B07C": "Postal sorting; Sorting individual articles; or bulk material fit to be sorted piece-meal; e.g. by picking",
        "B08": "CLEANING",
        "B08B": "Cleaning in general; Prevention of fouling in general",
        "B09": "DISPOSAL OF SOLIDWASTE; RECLAMATION OF CONTAMINATED SOIL",
        "B09B": "Disposal of solid waste",
        "B09C": "Reclamation of contaminated soil",
        "B21": "MECHANICALMETAL-WORKING WITHOUT ESSENTIALLY REMOVING MATERIAL; PUNCHINGMETAL",
        "B21B": "Rolling of metal",
        "B21C": "Manufacture of metal sheets; wire; rods; tubes or profiles; otherwise than by rolling; Auxiliary operations used in connection with metal-working without essentially removing material",
        "B21D": "Working or processing of sheet metal or metal tubes; rods or profiles without essentially removing material; Punching",
        "B21F": "Working or processing of wire",
        "B21G": "Making needles; pins; or nails",
        "B21H": "Making particular metal objects by rolling; e.g. screws; wheels; rings; barrels; balls",
        "B21J": "Forging; Hammering; Pressing; Riveting; Forge furnaces",
        "B21K": "Making forged or pressed products; e.g. horseshoes; rivets; bolts; wheels",
        "B21L": "Making chains",
        "B22": "CASTING; POWDER METALLURGY",
        "B22C": "Foundry moulding",
        "B22D": "Casting of metals; Casting of other substances by the same processes or devices",
        "B22F": "Working metallic powder; Manufacture of articles from metallic powder; Making metallic powder",
        "B23": "MACHINE TOOLS; METAL-WORKING NOT OTHERWISE PROVIDED FOR",
        "B23B": "Turning; Boring",
        "B23C": "Milling",
        "B23D": "Planing; Slotting; Shearing; Broaching; Sawing; Filing; Scraping; Like operations for working metal by removing material; not otherwise provided for",
        "B23F": "Making gears or toothed racks",
        "B23G": "Thread cutting; Working of screws; bolt heads; or nuts; in conjunction therewith",
        "B23H": "Working of metal by the action of a high concentration of electric current on a workpiece using an electrode which takes the place of a tool; Such working combined with other forms of working of metal",
        "B23K": "Soldering or unsoldering; Welding; Cladding or plating by soldering or welding; Cutting by applying heat locally; e.g. flame cutting; Working by laser beam",
        "B23P": "Other working of metal; Combined operations; Universal machine tools",
        "B23Q": "Details; components; or accessories for machine tools; e.g. arrangements for copying or controlling; Machine tools in general; characterised by the construction of particular details or components; Combinations or associations of metal-working machines; not directed to a particular result",
        "B24": "GRINDING; POLISHING",
        "B24B": "Machines; devices; or processes for grinding or polishing; Dressing or conditioning of abrading surfaces; Feeding of grinding; polishing; or lapping agents",
        "B24C": "Abrasive or related blasting with particulate material",
        "B24D": "Tools for grinding; buffing; or sharpening",
        "B25": "HAND TOOLS; PORTABLE POWERDRIVEN TOOLS; HANDLES FOR HAND IMPLEMENTS;WORKSHOP EQUIPMENT; MANIPULATORS",
        "B25B": "Tools or bench devices not otherwise provided for; for fastening; connecting; disengaging; or holding",
        "B25C": "Hand-held nailing or stapling tools; Manuallyoperated portable stapling tools",
        "B25D": "Percussive tools",
        "B25F": "Combination or multi-purpose tools not otherwise provided for; Details or components of portable power-driven tools not particularly related to the operations performed and not otherwise provided for",
        "B25G": "Handles for hand implements",
        "B25H": "Workshop equipment; e.g. for marking-out work; Storage means for workshops",
        "B25J": "Manipulators; Chambers provided with manipulation devices",
        "B26": "HAND CUTTING TOOLS; CUTTING; SEVERING",
        "B26B": "Hand-held cutting tools not otherwise provided for",
        "B26D": "Cutting; Details common to machines for severing; e.g. by cutting; perforating; punching; stamping-out",
        "B26F": "Perforating; Punching; Cutting-out; Stamping-out; Severing by means other than cutting",
        "B27": "WORKING OR PRESERVINGWOOD OR SIMILAR MATERIAL; NAILING OR STAPLINGMACHINES IN GENERAL",
        "B27B": "Saws; Components or accessories therefor",
        "B27C": "Planing; drilling; milling; turning; or universal machines",
        "B27D": "Working veneer or plywood",
        "B27F": "Dovetailed work; Tenons; Slotting machines; Nailing or stapling machines",
        "B27G": "Accessory machines or apparatus; Tools; Safety devices; e.g. for saws",
        "B27H": "Bending; Cooperage; Wheel-making",
        "B27J": "Mechanical working of cane; cork; or similar materials",
        "B27K": "Processes; apparatus or selection of substances for impregnating; staining; dyeing; bleaching of wood or similar materials; or treating of wood or similar materials with permeant liquids; not otherwise provided for; Chemical or physical treatment of cork; cane; reed; straw or similar materials",
        "B27L": "Removing bark or vestiges of branches; Splitting wood; Manufacture of veneer; wooden sticks; wood shavings; wood fibres or wood powder",
        "B27M": "Working of wood not provided for in subclasses",
        "B27B": "to L; Manufacture of specific wooden articles",
        "B27N": "Manufacture by dry processes of articles; with or without organic binding agents; made from particles or fibres consisting of wood or other lignocellulosic or like organic material",
        "B28": "WORKING CEMENT; CLAY; OR STONE",
        "B28B": "Shaping clay or other ceramic compositions; slag or mixtures containing cementitious material; e.g. plaster",
        "B28C": "Preparing clay; Producing mixtures containing clay or cementitious material; e.g. plaster",
        "B28D": "Working stone or stone-like materials",
        "B29": "WORKING OF PLASTICS;WORKING OF SUBSTANCES IN A PLASTIC STATE IN GENERAL",
        "B29B": "Preparation or pretreatment of the material to be shaped; Making granules or preforms; Recovery of plastics or other constituents of waste material containing plastics",
        "B29C": "Shaping or joining of plastics; Shaping of substances in a plastic state; in general; Aftertreatment of the shaped products; e.g. repairing",
        "B29D": "Producing particular articles from plastics or from substances in a plastic state",
        "B29K": "Indexing scheme associated with subclasses",
        "B29": "B; C or D; relating to moulding materials or to materials for reinforcements; fillers or preformed parts; e.g. inserts",
        "B29L": "Indexing scheme associated with subclass B 29 C; relating to particular articles",
        "B30": "PRESSES",
        "B30B": "Presses in general",
        "B31": "MAKING PAPER ARTICLES;WORKING PAPER",
        "B31B": "Making boxes; cartons; envelopes; or bags",
        "B31C": "Making wound articles; e.g. wound tubes",
        "B31D": "Making other paper articles",
        "B31F": "Mechanical working or deformation of paper or cardboard",
        "B32": "LAYERED PRODUCTS",
        "B32B": "Layered products; i.e. products built-up of strata of flat or non-flat; e.g. cellular or honeycomb; form",
        "B41": "PRINTING; LININGMACHINES; TYPEWRITERS; STAMPS",
        "B41B": "Machines or accessories for making; setting; or distributing type; Type; Photographic or photoelectronic composing devices",
        "B41C": "Processes for the manufacture or reproduction of printing surfaces",
        "B41D": "Apparatus for the mechanical reproduction of printing surfaces for stereotype printing; Shaping elastic or deformable material to form printing surfaces",
        "B41F": "Printing machines or presses",
        "B41G": "Apparatus for bronze printing; line printing; or for bordering or edging sheets or like articles; Auxiliary apparatus for perforating in conjunction with printing",
        "B41J": "Typewriters; Selective printing mechanisms; i.e. mechanisms printing otherwise than from a forme; Correction of typographical errors",
        "B41K": "Stamps; Stamping or numbering apparatus or devices",
        "B41L": "Apparatus or devices for manifolding; duplicating; or printing for office or other commercial purposes; Addressing machines or like seriesprinting machines",
        "B41M": "Printing; duplicating; marking; or copying processes; Colour printing",
        "B41N": "Printing plates or foils; Materials for surfaces used in printing machines for printing; inking; damping; or the like; Preparing such surfaces for use or conserving them",
        "B42": "BOOKBINDING; ALBUMS; FILES; SPECIAL PRINTED MATTER",
        "B42B": "Permanently attaching together sheets; quires; or signatures; or permanently attaching objects thereto",
        "B42C": "Bookbinding",
        "B42D": "Books; Book covers; Loose leaves; Printed matter of special format or style not otherwise provided for; Devices for use therewith; Movable-strip writing or reading apparatus",
        "B42F": "Sheets temporarily attached together; Filing appliances; File cards; Indexing",
        "B43": "WRITING OR DRAWING IMPLEMENTS; BUREAU ACCESSORIES",
        "B43K": "Implements for writing or drawing",
        "B43L": "Articles for writing or drawing upon; Accessories for writing or drawing",
        "B43M": "Bureau accessories not otherwise provided for",
        "B44": "DECORATIVE ARTS",
        "B44B": "Machines; apparatus; or tools for artistic work; e.g. for sculpturing; guilloching; carving; branding; inlaying",
        "B44C": "Producing decorative effects; Mosaics; Tarsia work; Paperhanging",
        "B44D": "Painting or artistic drawing; not otherwise provided for; Preserving paintings; Surface treatment to obtain special artistic surface effects or finishes",
        "B44F": "Special designs or pictures",
        "B60": "VEHICLES IN GENERAL",
        "B60B": "Vehicle wheels; Castors; Axles; Increasing wheel adhesion",
        "B60C": "Vehicle tyres; Tyre inflation; Tyre changing; Connecting valves to inflatable elastic bodies in general; Devices or arrangements related to tyres",
        "B60D": "Vehicle connections",
        "B60F": "Vehicles for use both on rail and on road; Amphibious or like vehicles; Convertible vehicles",
        "B60G": "Vehicle suspension arrangements",
        "B60H": "Arrangements or adaptations of heating; cooling; ventilating; or other air-treating devices specially for passenger or goods spaces of vehicles",
        "B60J": "Windows; windscreens; non-fixed roofs; doors; or similar devices for vehicles; Protective coverings for vehicles not in use",
        "B60K": "Arrangement or mounting of propulsion units or of transmissions in vehicles; Arrangement or mounting of plural diverse prime-movers; Auxiliary drives; Instrumentation or dashboards for vehicles; Conjoint control of drive units; Arrangements in connection with cooling; air intake; gas exhaust; or fuel supply; of propulsion units; in vehicles",
        "B60L": "Electric equipment or propulsion of electricallypropelled vehicles; Magnetic suspension or levitation for vehicles; Electrodynamic brake systems for vehicles; in general",
        "B60M": "Power supply lines; or devices along rails; for electrically-propelled vehicles",
        "B60N": "Vehicle passenger accommodation not otherwise provided for",
        "B60P": "Vehicles adapted for load transportation or to transport; to carry; or to comprise special loads or objects",
        "B60Q": "Arrangement of signalling or lighting devices; the mounting or supporting thereof or circuits therefor; for vehicles in general",
        "B60R": "Vehicles; vehicle fittings; or vehicle parts; not otherwise provided for",
        "B60S": "Servicing; cleaning; repairing; supporting; lifting; or manoeuvring of vehicles; not otherwise provided for",
        "B60T": "Vehicle brake control systems or parts thereof; Brake control systems; or parts thereof; in general",
        "B60V": "Air-cushion vehicles",
        "B61": "RAILWAYS",
        "B61B": "Railway systems; Equipment therefor not otherwise provided for",
        "B61C": "Locomotives; Motor railcars",
        "B61D": "Body details or kinds of railway vehicles",
        "B61F": "Rail vehicle suspensions; e.g. underframes; bogies; arrangements of wheel axles; Rail vehicles for use on tracks of different width; Preventing derailing; Wheels guards; Obstruction removers or the like",
        "B61G": "Couplings; Draught or buffing appliances",
        "B61H": "Brakes or other retarding apparatus peculiar to rail vehicles; Arrangements or dis-positions of brakes or other retarding apparatus in rail vehicles",
        "B61J": "Shifting or shunting of rail vehicles",
        "B61K": "Other auxiliary equipment for railways",
        "B61L": "Guiding railway traffic: ensuring the safety of railway traffic",
        "B62": "LAND VEHICLES FOR TRAVELLING OTHERWISE THAN ON RAILS",
        "B62B": "Hand-propelled vehicles; e.g. hand carts; perambulators; Sledges",
        "B62C": "Vehicles drawn by animals",
        "B62D": "Motor vehicles; Trailers",
        "B62H": "Cycle stands; Supports or holders for parking or storing cycles; Appliances preventing or indicating unauthorised use or theft of cycles; Locks integral with cycles; Devices for learning to ride cycles",
        "B62J": "Cycle saddles or seats; Accessories peculiar to cycles and not otherwise provided for; e.g. article carriers; cycle protectors",
        "B62K": "Cycles; Cycle frames; Cycle steering devices; Rider-operated terminal controls specially adapted for cycles; Cycle axle suspensions; Cycle sidecars; forecars; or the like",
        "B62L": "Brakes specially adapted for cycles",
        "B62M": "Rider propulsion of wheeled vehicles or sledges; Powered propulsion of sledges or cycles; Transmissions specially adapted for such vehicles",
        "B63": "SHIPS OR OTHERWATERBORNE VESSELS; RELATED EQUIPMENT",
        "B63B": "Ships or other waterborne vessels; Equipment for shipping",
        "B63C": "Launching; hauling-out; or dry-docking of vessels; Life-saving in water; Equipment for dwelling or working under water; Means for salvaging or searching for underwater objects",
        "B63G": "Offensive or defensive arrangements on vessels; Mine-laying; Mine-sweeping; Submarines; Aircraft carriers",
        "B63H": "Marine propulsion or steering",
        "B63J": "Auxiliaries on vessels",
        "B64": "AIRCRAFT; AVIATION; COSMONAUTICS",
        "B64B": "Lighter-than-air aircraft",
        "B64C": "Aeroplanes; Helicopters",
        "B64D": "Equipment for fitting in or to aircraft; Flying suits; Parachutes; Arrangements or mounting of power plants or propulsion transmissions",
        "B64F": "Ground or aircraft-carrier-deck installations",
        "B64G": "Cosmonautics; Vehicles or equipment therefor",
        "B65": "CONVEYING; PACKING; STORING; HANDLING THIN OR FILAMENTARY MATERIAL",
        "B65B": "Machines; apparatus or devices for; or methods of; packaging articles or materials; Unpacking",
        "B65C": "Labelling or tagging machines; apparatus; or processes",
        "B65D": "Containers for storage or transport of articles or materials; e.g. bags; barrels; bottles; boxes; cans; cartons; crates; drums; jars; tanks; hoppers; forwarding containers; Accessories; closures; or fittings therefor; Packaging elements; Packages",
        "B65F": "Gathering or removal of domestic or like refuse",
        "B65G": "Transport or storage devices; e.g. conveyers for loading or tipping; Shop conveyer systems; Pneumatic tube conveyers",
        "B65H": "Handling thin or filamentary material; e.g. sheets; webs; cables",
        "B66": "HOISTING; LIFTING; HAULING",
        "B66B": "Elevators; Escalators or moving walkways",
        "B66C": "Cranes; Load-engaging elements or devices for cranes; capstans; winches; or tackles",
        "B66D": "Capstans; Winches; Tackles; e.g. pulley blocks; Hoists",
        "B66F": "Hoisting; lifting; hauling; or pushing; not otherwise provided for; e.g. devices which apply a lifting or pushing force directly to the surface of a load",
        "B67": "OPENING OR CLOSING BOTTLES; JARS OR SIMILAR CONTAINERS; LIQUID HANDLING",
        "B67B": "Applying closure members to bottles; jars; or similar containers; Opening closed containers",
        "B67C": "Filling with liquids or semiliquids; or emptying; of bottles; jars; cans; casks; barrels; or similar containers; not otherwise provided for; Funnels",
        "B67D": "Dispensing; delivering; or transferring liquids; not otherwise provided for",
        "B68": "SADDLERY; UPHOLSTERY",
        "B68B": "Harness; Devices used in connection therewith; Whips or the like",
        "B68C": "Saddles; Stirrups",
        "B68F": "Making articles from leather; canvas; or the like",
        "B68G": "Methods; equipment; or machines for use in upholstering; Upholstery not otherwise provided for",
        "B81": "MICRO-STRUCTURAL TECHNOLOGY",
        "B81B": "Micro-structural devices or systems; e.g. micromechanical devices",
        "B81C": "Processes or apparatus specially adapted for the manufacture or treatment of micro-structural devices or systems",
        "B82": "NANO-TECHNOLOGY",
        "B82B": "Nano-structures; Manufacture or treatment thereof",
        "C01": "INORGANIC CHEMISTRY",
        "C01B": "Non-metallic elements; Compounds thereof",
        "C01C": "Ammonia; Cyanogen; Compounds thereof",
        "C01D": "Compounds of alkali metals; i.e. lithium; sodium; potassium; rubidium; caesium; or francium",
        "C01F": "Compounds of the metals beryllium; magnesium; aluminium; calcium; strontium; barium; radium; thorium; or of the rare-earth metals",
        "C01G": "Compounds containing metals not covered by subclasses C 01 D or F",
        "C02": "TREATMENT OFWATER;WASTEWATER; SEWAGE; OR SLUDGE",
        "C02F": "Treatment of water; waste water; sewage; or sludge",
        "C03": "GLASS; MINERAL OR SLAGWOOL",
        "C03B": "Manufacture; shaping; or supplementary processes",
        "C03C": "Chemical composition of glasses; glazes; or vitreous enamels; Surface treatment of glass; Surface treatment of fibres or filaments from glass; minerals or slags; Joining glass to glass or other materials",
        "C04": "CEMENTS; CONCRETE; ARTIFICIAL STONE; CERAMICS; REFRACTORIES",
        "C04B": "Lime; Magnesia; Slag; Cements; Compositions thereof; e.g. mortars; concrete or like building materials; Artificial stone; Ceramics; Refractories; Treatment of natural stone",
        "C05": "FERTILISERS; MANUFACTURE THEREOF",
        "C05B": "Phosphatic fertilisers",
        "C05C": "Nitrogenous fertilisers",
        "C05D": "Inorganic fertilisers not covered by subclasses C 05 B; C; Fertilisers producing carbon dioxide",
        "C05F": "Organic fertilisers not covered by subclasses C 05 B; C; e.g. fertilisers from waste or refuse",
        "C05G": "Mixtures of fertilisers covered individually by different subclasses of class C 05; Mixtures of one or more fertilisers with materials not having a specific fertilising activity; e.g. pesticides; soilconditioners; wetting agents; Fertilisers characterised by their form",
        "C06": "EXPLOSIVES; MATCHES",
        "C06B": "Explosive or thermic compositions; Manufacture thereof; Use of single substances as explosives",
        "C06C": "Detonating or priming devices; Fuses; Chemical lighters; Pyrophoric compositions",
        "C06D": "Means for generating smoke or mist; Gas-attack compositions; Generation of gas for blasting or propulsion",
        "C06F": "Matches; Manufacture of matches",
        "C07": "ORGANIC CHEMISTRY",
        "C07B": "General methods of organic chemistry; Apparatus therefor",
        "C07C": "Acyclic or carbocyclic compounds",
        "C07D": "Heterocyclic compounds",
        "C07F": "Acyclic; carbocyclic; or heterocyclic compounds containing elements other than carbon; hydrogen; halogen; oxygen; nitrogen; sulfur; selenium; or tellurium",
        "C07G": "Compounds of unknown constitution",
        "C07H": "Sugars; Derivatives thereof; Nucleosides; Nucleotides; Nucleic acids",
        "C07J": "Steroids",
        "C07K": "Peptides",
        "C07M": "Indexing scheme associated with subclasses C 07 B to K; relating to specific properties of organic compounds",
        "C08": "ORGANIC MACROMOLECULAR COMPOUNDS; THEIR PREPARATION OR CHEMICALWORKING-UP; COMPOSITIONS BASED THEREON",
        "C08B": "Polysaccharides; Derivatives thereof",
        "C08C": "Treatment or chemical modification of rubbers",
        "C08F": "Macromolecular compounds obtained by reactions only involving carbon-to-carbon unsaturated bonds",
        "C08G": "Macromolecular compounds obtained otherwise than by reactions only involving carbon-to-carbon unsaturated bonds",
        "C08H": "Derivatives of natural macromolecular compounds",
        "C08J": "Working-up; General processes of compounding; After-treatment not covered by subclasses C 08 B; C; F; G",
        "C08K": "Use of inorganic or non-macromolecular organic substances as compounding ingredients",
        "C08L": "Compositions of macromolecular compounds",
        "C09": "DYES; PAINTS; POLISHES; NATURAL RESINS; ADHESIVES; MISCELLANEOUS COMPOSITIONS; MISCELLANEOUS APPLICATIONS OFMATERIALS",
        "C09B": "Organic dyes or closely-related compounds for producing dyes; Mordants; Lakes",
        "C09C": "Treatment of inorganic materials; other than fibrous fillers; to enhance their pigmenting or filling properties; Preparation of carbon black",
        "C09D": "Coating compositions; e.g. paints; varnishes; lacquers; Filling pastes; Chemical paint or ink removers; Inks; Correcting fluids; Woodstains; Pastes or solids for colouring or printing; Use of materials therefor",
        "C09F": "Natural resins; French polish; Drying-oils; Driers; Turpentine",
        "C09G": "Polishing compositions other than french polish; Ski waxes",
        "C09H": "Preparation of glue or gelatine",
        "C09J": "Adhesives; Adhesive processes in general; Adhesive processes not provided for elsewhere; Use of materials as adhesives",
        "C09K": "Materials for miscellaneous applications; not provided for elsewhere",
        "C10": "PETROLEUM; GAS OR COKE INDUSTRIES; TECHNICAL GASES CONTAINING CARBON MONOXIDE; FUELS; LUBRICANTS; PEAT",
        "C10B": "Destructive distillation of carbonaceous materials for production of gas; coke; tar; or similar materials",
        "C10C": "Working-up tar; pitch; asphalt; bitumen; Pyroligneous acid",
        "C10F": "Drying or working-up of peat",
        "C10G": "Cracking hydrocarbon oils; Production of liquid hydrocarbon mixtures; e.g. by destructive hydrogenation; oligomerisation; polymerisation; Recovery of hydrocarbon oils from oil-shale; oilsand; or gases; Refining mixtures mainly consisting of hydrocarbons; Reforming of naphtha; Mineral waxes",
        "C10H": "Production of acetylene by wet methods",
        "C10J": "Production of producer gas; water-gas; synthesis gas from solid carbonaceous material; or mixtures containing these gases; Carburetting air or other gases",
        "C10K": "Purifying or modifying the chemical compositions of combustible gases containing carbon monoxide",
        "C10L": "Fuels not otherwise provided for; Natural gas; Synthetic natural gas obtained by processes not covered by subclasses C 10 G; K; Liquefied petroleum gas; Adding materials to fuels or fires to reduce smoke or undesirable deposits or to facilitate soot removal; Fire-lighters",
        "C10M": "Lubricating compositions; Use of chemical substances either alone or as lubricating ingredients in a lubricating composition",
        "C10N": "Indexing scheme associated with subclass C 10M",
        "C11": "ANIMAL OR VEGETABLE OILS; FATS; FATTY SUBSTANCES ORWAXES; FATTY ACIDS THEREFROM; DETERGENTS; CANDLES",
        "C11B": "Producing; refining or preserving fats; fatty substances; fatty oils or waxes; including extraction from waste materials; Essential oils; Perfumes",
        "C11C": "Fatty acids from fats; oils or waxes; Candles; Fats; oils or fatty acids by chemical modification of fats; oils; or fatty acids obtained therefrom",
        "C11D": "Detergent compositions; Use of single substances as detergents; Soap or soap-making; Resin soaps; Recovery of glycerol",
        "C12": "BIOCHEMISTRY; BEER; SPIRITS;WINE; VINEGAR; MICROBIOLOGY; ENZYMOLOGY; MUTATION OR GENETIC ENGINEERING",
        "C12C": "Brewing of beer",
        "C12F": "Recovery of by-products of fermented solutions; Denaturing of; or denatured; alcohol",
        "C12G": "Wine; Other alcoholic beverages; Preparation thereof",
        "C12H": "Pasteurisation; sterilisation; preservation; purification; clarification; ageing of alcoholic beverages or removal of alcohol therefrom",
        "C12J": "Vinegar; Its preparation",
        "C12L": "Pitching or depitching machines; Cellar tools",
        "C12M": "Apparatus for enzymology or microbiology",
        "C12N": "Micro-organisms or enzymes; Compositions thereof; Propagating; preserving; or maintaining micro-organisms; Mutation or genetic engineering; Culture media",
        "C12P": "Fermentation or enzyme-using processes to synthesise a desired chemical compound or composition or to separate optical isomers from a racemic mixture",
        "C12Q": "Measuring or testing processes involving enzymes or micro-organisms; Compositions or test papers therefor; Processes of preparing such compositions; Condition-responsive control in microbiological or enzymological processes",
        "C12R": "Indexing scheme associated with subclasses C 12 C to Q or S; relating to micro-organisms",
        "C12S": "Processes using enzymes or micro-organisms to liberate; separate or purify a pre-existing compound or composition; Processes using enzymes or micro-organisms to treat textiles or to clean solid surfaces of materials",
        "C13": "SUGAR INDUSTRY",
        "C13C": "Cutting mills; Shredding knives; Pulp presses",
        "C13D": "Production or purification of sugar juices",
        "C13F": "Preparation or processing of raw sugar; sugar; or syrup",
        "C13G": "Evaporation apparatus; Boiling pans",
        "C13H": "Cutting machines for sugar; Combined cutting; sorting and packing machines for sugar",
        "C13J": "Extraction of sugar from molasses",
        "C13K": "Glucose; Invert sugar; Lactose; Maltose; Synthesis of sugars by hydrolysis of di- or polysaccharides",
        "C14": "SKINS; HIDES; PELTS; LEATHER",
        "C14B": "Mechanical treatment or processing of skins; hides; or leather in general; Pelt-shearing machines; Intestine-splitting machines",
        "C14C": "Chemical treatment of hides; skins or leather; e.g. tanning; impregnating; finishing; Apparatus therefor; Compositions for tanning",
        "C21": "METALLURGY OF IRON",
        "C21B": "Manufacture of iron or steel",
        "C21C": "Processing of pig-iron; e.g. refining; manufacture of wrought-iron or steel; Treatment in molten state of ferrous alloys",
        "C21D": "Modifying the physical structure of ferrous metals; General devices for heat treatment of ferrous or non-ferrous metals or alloys; Making metal malleable by decarburisation; tempering; or other treatments",
        "C22": "METALLURGY; FERROUS OR NONFERROUS ALLOYS; TREATMENT OF ALLOYS OR NON-FERROUS METALS",
        "C22B": "Production or refining of metals; Pretreatment of raw materials",
        "C22C": "Alloys",
        "C22F": "Changing the physical structure of non-ferrous metals or non-ferrous alloys",
        "C22K": "Indexing scheme associated with subclasses C 21 D; C 22 C or F; relating to changing the physical characteristics of alloys",
        "C23": "COATINGMETALLIC MATERIAL; COATINGMATERIALWITH METALLIC MATERIAL; CHEMICAL SURFACE TREATMENT; DIFFUSION TREATMENT OFMETALLIC MATERIAL; COATING BY VACUUM EVAPORATION; BY SPUTTERING; BY ION IMPLANTATION OR BY CHEMICAL VAPOUR DEPOSITION; IN GENERAL; INHIBITING CORROSION OF METALLIC MATERIAL OR INCRUSTATION IN GENERAL",
        "C23C": "Coating metallic material; Coating material with metallic material; Surface treatment of metallic material by diffusion into the surface; by chemical conversion or substitution; Coating by vacuum evaporation; by sputtering; by ion implantation or by chemical vapour deposition; in general",
        "C23D": "Enamelling of; or applying a vitreous layer to; metals",
        "C23F": "Non-mechanical removal of metallic material from surfaces; Inhibiting corrosion of metallic material; Inhibiting incrustation in general; Multi-step processes for surface treatment of metallic material involving at least one process provided for in class C 23 and at least one process covered by subclass C 21 Dor C 22 F or class C 25",
        "C23G": "Cleaning or de-greasing of metallic material by chemical methods other than electrolysis",
        "C25": "ELECTROLYTIC OR ELECTROPHORETIC PROCESSES; APPARATUS THEREFOR",
        "C25B": "Electrolytic or electrophoretic processes for the production of compounds or non- metals; Apparatus therefor",
        "C25C": "Processes for the electrolytic production; recovery or refining of metals; Apparatus therefor",
        "C25D": "Processes for the electrolytic or electrophoretic production of coatings; Electroforming; Joining workpieces by electrolysis; Apparatus therefor",
        "C25F": "Processes for the electrolytic removal of materials from objects; Apparatus therefor",
        "C30": "CRYSTAL GROWTH",
        "C30B": "Single-crystal growth; Unidirectional solidification of eutectic material or unidirectional demixing of eutectoid material; Refining by zonemelting of material; Production of a homogeneous polycrystalline material with defined structure; Single crystals or homogeneous polycrystalline material with defined structure; After-treatment of single crystals or a homogeneous polycrystalline material with defined structure; Apparatus therefor",
        "D01": "NATURAL OR ARTIFICIAL THREADS OR FIBRES; SPINNING",
        "D01B": "Mechanical treatment of natural fibrous or filamentary material to obtain fibres or filaments; e.g. for spinning",
        "D01C": "Chemical treatment of natural filamentary or fibrous material to obtain filaments or fibres for spinning; Carbonising rags to recover animal fibres",
        "D01D": "Mechanical methods or apparatus in the manufacture of artificial filaments; threads; fibres; bristles; or ribbons",
        "D01F": "Chemical features in the manufacture of artificial filaments; threads; fibres; bristles; or ribbons; Apparatus specially adapted for the manufacture of carbon filaments",
        "D01G": "Preliminary treatment of fibres; e.g. for spinning",
        "D01H": "Spinning or twisting",
        "D02": "YARNS; MECHANICAL FINISHING OF YARNS OR ROPES;WARPING OR BEAMING",
        "D02G": "Crimping or curling fibres; filaments; yarns; or threads; Yarns or threads",
        "D02H": "Warping; beaming; or leasing",
        "D02J": "Finishing or dressing of filaments; yarns; threads; cords; ropes; or the like",
        "D03": "WEAVING",
        "D03C": "Shedding mechanisms; Pattern cards or chains; Punching of cards; Designing patterns",
        "D03D": "Woven fabrics; Methods of weaving; Looms",
        "D03J": "Auxiliary weaving apparatus; Weavers' tools; Shuttles",
        "D04": "BRAIDING; LACE-MAKING; KNITTING; TRIMMINGS; NON-WOVEN FABRICS",
        "D04B": "Knitting",
        "D04C": "Braiding or manufacture of lace; including bobbinnet or carbonised lace; Braiding machines; Braid; Lace",
        "D04D": "Trimmings; Ribbons; tapes; or bands; not otherwise provided for",
        "D04G": "Making nets by knotting of filamentary material; Making knotted carpets or tapestries; Knotting not otherwise provided for",
        "D04H": "Making textile fabrics; e.g. from fibres or filamentary material; Fabrics made by such processes or apparatus; e.g. felts; non-woven fabrics; Cotton-wool;Wadding",
        "D05": "SEWING; EMBROIDERING; TUFTING",
        "D05B": "Sewing",
        "D05C": "Embroidering; Tufting",
        "D06": "TREATMENT OF TEXTILES OR THE LIKE; LAUNDERING; FLEXIBLE MATERIALS NOT OTHERWISE PROVIDED FOR",
        "D06B": "Treating textile materials by liquids; gases; or vapours",
        "D06C": "Finishing; dressing; tentering; or stretching textile fabrics",
        "D06F": "Laundering; drying; ironing; pressing or folding textile articles",
        "D06G": "Mechanical or pressure cleaning of carpets; rugs; sacks; hides; or other skin or textile articles or fabrics; Turning inside-out flexible tubular or other hollow articles",
        "D06H": "Marking; inspecting; seaming; or severing textile materials",
        "D06J": "Pleating; kilting; or goffering textile fabrics or wearing apparel",
        "D06L": "Bleaching; e.g. optical bleaching; dry-cleaning; or washing fibres; threads; yarns; fabrics; feathers; or made-up fibrous goods; Bleaching leather or furs",
        "D06M": "Treatment; not provided for elsewhere in class D 06; of fibres; threads; yarns; fabrics; feathers; or fibrous goods made from such materials",
        "D06N": "Wall; floor; or like covering materials; e.g. linoleum; oilcloth; artificial leather; roofing felt; consisting of a fibrous web coated with a layer of macromolecular material; Flexible sheet material not otherwise provided for",
        "D06P": "Dyeing or printing textiles; Dyeing leather; furs; or solid macromolecular substances in any form",
        "D06Q": "Decorating textiles",
        "D07": "ROPES; CABLES OTHER THAN ELECTRIC",
        "D07B": "Ropes or cables in general",
        "D21": "PAPER-MAKING; PRODUCTION OF CELLULOSE",
        "D21B": "Fibrous raw materials or their mechanical treatment",
        "D21C": "Production of cellulose by removing non-cellulose substances from cellulose- containing materials; Regeneration of pulping liquors; Apparatus therefor",
        "D21D": "Treatment of the materials before passing to the paper-making machine",
        "D21F": "Paper-making machines; Methods of producing paper thereon",
        "D21G": "Calenders; Accessories for paper-making machines",
        "D21H": "Pulp compositions; Preparation thereof not covered by subclasses D 21 C; D; Impregnating or coating of paper; Treatment of finished paper not covered by class B 31 or subclass D 21 G; Paper not otherwise provided for",
        "D21J": "vFibreboard; Manufacture of articles from cellulosic fibrous suspensions or from papiermâché",
        "E01": "CONSTRUCTION OF ROADS; RAILWAYS; OR BRIDGES",
        "E01B": "Permanent way; Permanent-way tools; Machines for making railways of all kinds",
        "E01C": "Construction of; or surfaces for; roads; sports grounds; or the like; Machines or auxiliary tools for construction or repair",
        "E01D": "Bridges",
        "E01F": "Additional work; such as equipping roads or the construction of platforms; helicopter landing stages; signs; snow fences; or the like",
        "E01H": "Street cleaning; Cleaning of permanent ways; Cleaning beaches; Cleaning land; Dispersing fog in general",
        "E02": "HYDRAULIC ENGINEERING; FOUNDATIONS; SOIL-SHIFTING",
        "E02B": "Hydraulic engineering",
        "E02C": "Ship-lifting devices or mechanisms",
        "E02D": "Foundations; Excavations; Embankments; Underground or underwater structures",
        "E02F": "Dredging; Soil-shifting",
        "E03": "WATER SUPPLY; SEWERAGE",
        "E03B": "Installations or methods for obtaining; collecting; or distributing water",
        "E03C": "Domestic plumbing installations for fresh water or waste water; Sinks",
        "E03D": "Water-closets or urinals with flushing devices; Flushing valves therefor",
        "E03F": "Sewers; Cesspools",
        "E04": "BUILDING",
        "E04B": "General building constructions;Walls; e.g. partitions; Roofs; Floors; Ceilings; Insulation or other protection of buildings",
        "E04C": "Structural elements; Building materials",
        "E04D": "Roof coverings; Sky-lights; Gutters; Roof-working tools",
        "E04F": "Finishing work on buildings; e.g. stairs; floors",
        "E04G": "Scaffolding; Forms; Shuttering; Building implements or other building aids; or their use; Handling building materials on the site; Repairing; breaking-up or other work on existing buildings",
        "E04H": "Buildings or like structures for particular purposes; Swimming or splash baths or pools; Masts; Fencing; Tents or canopies; in general",
        "E05": "LOCKS; KEYS;WINDOWOR DOOR FITTINGS; SAFES",
        "E05B": "Locks; Accessories therefor; Handcuffs",
        "E05C": "Bolts or fastening devices for wings; specially for doors or windows",
        "E05D": "Hinges or other suspension devices for doors; windows; or wings",
        "E05F": "Devices for moving wings into open or closed position; Checks for wings; Wing fittings not otherwise provided for; concerned with the functioning of the wing",
        "E05G": "Safes or strong-rooms for valuables; Bank protection devices; Safety transaction partitions",
        "E06": "DOORS;WINDOWS; SHUTTERS; OR ROLLER BLINDS; IN GENERAL; LADDERS",
        "E06B": "Fixed or movable closures for openings in buildings; vehicles; fences; or like enclosures; in general; e.g. doors; windows; blinds; gates",
        "E06C": "Ladders",
        "E21": "EARTH OR ROCK DRILLING; MINING",
        "E21B": "Earth or rock drilling; Obtaining oil; gas; water; soluble or meltable materials or a slurry of minerals from wells",
        "E21C": "Mining or quarrying",
        "E21D": "Shafts; Tunnels; Galleries; Large underground chambers",
        "E21F": "Safety devices; transport; filling-up; rescue; ventilation; or drainage in or of mines or tunnels",
        "F01": "MACHINES OR ENGINES IN GENERAL; ENGINE PLANTS IN GENERAL; STEAM ENGINES",
        "F01B": "Machines or engines; in general or of positivedisplacement type; e.g. steam engines",
        "F01C": "Rotary-piston or oscillating-piston machines or engines",
        "F01D": "Non-positive-displacement machines or engines; e.g. steam turbines",
        "F01K": "Steam engine plants; Steam accumulators; Engine plants not otherwise provided for; Engines using special working fluids or cycles",
        "F01L": "Cyclically operating valves for machines or engines",
        "F01M": "Lubricating of machines or engines in general; Lubricating internal-combustion engines; Crankcase ventilating",
        "F01N": "Gas-flow silencers or exhaust apparatus for machines or engines in general; Gas-flow silencers or exhaust apparatus for internal-combustion engines",
        "F01P": "Cooling of machines or engines in general; Cooling of internal-combustion engines",
        "F02": "COMBUSTION ENGINES; HOT-GAS OR COMBUSTION-PRODUCT ENGINE PLANTS",
        "F02B": "Internal-combustion piston engines; Combustion engines in general",
        "F02C": "Gas-turbine plants; Air intakes for jet-propulsion plants; Controlling fuel supply in air-breathing jetpropulsion plants",
        "F02D": "Controlling combustion engines",
        "F02F": "Cylinders; pistons; or casings for combustion engines; Arrangements of sealings in combustion engines",
        "F02G": "Hot-gas or combustion-product positivedisplacement engine plants; Use of waste heat of combustion engines; not otherwise provided for",
        "F02K": "Jet-propulsion plants",
        "F02M": "Supplying combustion engines in general with combustible mixtures or constituents thereof",
        "F02N": "Starting of combustion engines; Starting aids for such engines; not otherwise provided for",
        "F02P": "Ignition; other than compression ignition; for internal-combustion engines; Testing of ignition timing in compression-ignition engines",
        "F03": "MACHINES OR ENGINES FOR LIQUIDS; WIND; SPRING; WEIGHT; OR MISCELLANEOUS MOTORS; PRODUCING MECHANICAL POWER OR A REACTIVE PROPULSIVE THRUST; NOT OTHERWISE PROVIDED FOR",
        "F03B": "Machines or engines for liquids",
        "F03C": "Positive-displacement engines driven by liquids",
        "F03D": "Wind motors",
        "F03G": "Spring; weight; inertia; or like motors; Mechanical-power-producing devices or mechanisms; not otherwise provided for or using energy sources not otherwise provided for",
        "F03H": "Producing a reactive propulsive thrust; not otherwise provided for",
        "F04": "POSITIVE-DISPLACEMENT MACHINES FOR LIQUIDS; PUMPS FOR LIQUIDS OR ELASTIC FLUIDS",
        "F04B": "Positive-displacement machines for liquids; Pumps",
        "F04C": "Rotary-piston; or oscillating-piston; positivedisplacement machines for liquids; Rotary-piston; or oscillating-piston; positive-displacement pumps",
        "F04D": "Non-positive-displacement pumps",
        "F04F": "Pumping of fluid by direct contact of another fluid or by using inertia of fluid to be pumped; Siphons",
        "F15": "FLUID-PRESSURE ACTUATORS; HYDRAULICS OR PNEUMATICS IN GENERAL",
        "F15B": "Systems acting by means of fluids in general; Fluid-pressure actuators; e.g. servomotors; Details of fluid-pressure systems; not otherwise provided for",
        "F15C": "Fluid-circuit elements predominantly used for computing or control purposes",
        "F15D": "Fluid dynamics; i.e. methods or means for influencing the flow of gases or liquids",
        "F16": "ENGINEERING ELEMENTS OR UNITS; GENERALMEASURES FOR PRODUCING AND MAINTAINING EFFECTIVE FUNCTIONING OFMACHINES OR INSTALLATIONS; THERMAL INSULATION IN GENERAL",
        "F16B": "Devices for fastening or securing constructional elements or machine parts together; e.g. nails; bolts; circlips; clamps; clips; wedges; Joints or jointing",
        "F16C": "Shafts; Flexible shafts; Elements of crankshaft mechanisms; Rotary bodies other than gearing elements; Bearings",
        "F16D": "Couplings for transmitting rotation; Clutches; Brakes",
        "F16F": "Springs; Shock-absorbers; Means for damping vibration",
        "F16G": "Belts; cables; or ropes; predominantly used for driving purposes; Chains; Fittings predominantly used therefor",
        "F16H": "Gearing",
        "F16J": "Pistons; Cylinders; Pressure vessels in general; Sealings",
        "F16K": "Valves; Taps; Cocks; Actuating-floats; Devices for venting or aerating",
        "F16L": "Pipes; Joints or fittings for pipes; Supports for pipes; cables or protective tubing; Means for thermal insulation in general",
        "F16M": "Frames; casings; or beds; of engines or other machines or apparatus; not specific to an engine; machine; or apparatus provided for elsewhere; Stands or supports",
        "F16N": "Lubricating",
        "F16P": "Safety devices in general",
        "F16S": "Constructional elements in general; Structures built-up from such elements; in general",
        "F16T": "Steam traps or like apparatus for draining-off liquids from enclosures predominantly containing gases or vapours",
        "F17": "STORING OR DISTRIBUTING GASES OR LIQUIDS",
        "F17B": "Gas-holders of variable capacity",
        "F17C": "Vessels for containing or storing compressed; liquefied; or solidified gases; Fixed-capacity gasholders; Filling vessels with; or discharging from vessels; compressed; liquefied; or solidified gases",
        "F17D": "Pipe-line systems; Pipe-lines",
        "F21": "LIGHTING",
        "F21H": "Incandescent mantles; Other incandescent bodies heated by combustion",
        "F21K": "Light sources not otherwise provided for",
        "F21L": "Lighting devices or systems thereof; being portable or specially adapted for transportation",
        "F21S": "Non-portable lighting devices or systems thereof",
        "F21V": "Functional features or details of lighting devices or systems thereof; Structural combinations of lighting devices with other articles; not otherwise provided for",
        "F21W": "Indexing scheme associated with subclasses F 21 L; S and V; relating to uses or applications of lighting devices or systems",
        "F21Y": "Indexing scheme associated with subclasses F 21 L; S and V; relating to the form of the light sources",
        "F22": "STEAM GENERATION",
        "F22B": "Methods of steam generation; Steam boilers",
        "F22D": "Preheating; or accumulating preheated; feed-water; Feed-water supply; Controlling water level; Circulating water within boilers",
        "F22G": "Superheating of steam",
        "F23": "COMBUSTION APPARATUS; COMBUSTION PROCESSES",
        "F23B": "Combustion apparatus using only solid fuel",
        "F23C": "Combustion apparatus using fluent fuel",
        "F23D": "Burners",
        "F23G": "Cremation furnaces; Consuming waste by combustion",
        "F23H": "Grates; Cleaning or raking grates",
        "F23J": "Removal or treatment of combustion products or combustion residues; Flues",
        "F23K": "Feeding fuel to combustion apparatus",
        "F23L": "Air supply; Draught-inducing; Supplying noncombustible liquid or gas",
        "F23M": "Constructional details of combustion chambers; not otherwise provided for",
        "F23N": "Regulating or controlling combustion",
        "F23Q": "Ignition; Extinguishing devices",
        "F23R": "Generating combustion products of high pressure or high velocity; e.g. gas-turbine combustion chambers",
        "F24": "HEATING; RANGES; VENTILATING",
        "F24B": "Domestic stoves or ranges for solid fuels; Implements for use in connection with stoves or ranges",
        "F24C": "Other domestic stoves or ranges; Details of domestic stoves or ranges; of general application",
        "F24D": "Domestic- or space-heating systems; e.g. central heating systems; Domestic hot-water supply systems; Elements or components therefor",
        "F24F": "Air-conditioning; Air-humidification; Ventilation; Use of air currents for screening",
        "F24H": "Fluid heaters; e.g. water or air heaters; having heat-generating means; in general",
        "F24J": "Production or use of heat not otherwise provided for",
        "F25": "REFRIGERATION OR COOLING; COMBINED HEATINGAND REFRIGERATION SYSTEMS; HEAT PUMP SYSTEMS; MANUFACTURE OR STORAGE OF ICE; LIQUEFACTION OR SOLIDIFICATION OF GASES",
        "F25B": "Refrigeration machines; plants; or systems; Combined heating and refrigeration systems; Heat pump systems",
        "F25C": "Production; working; storing; or distribution of ice",
        "F25D": "Refrigerators; Cold rooms; Ice-boxes; Cooling or freezing apparatus not covered by any other subclass",
        "F25J": "Liquefaction; solidification; or separation of gases or gaseous mixtures by pressure and cold treatment",
        "F26": "DRYING",
        "F26B": "Drying solid materials or objects by removing liquid therefrom",
        "F27": "FURNACES; KILNS; OVENS; RETORTS",
        "F27B": "Furnaces; kilns; ovens; or retorts in general; Open sintering or like apparatus",
        "F27D": "Details or accessories of furnaces; kilns; ovens; or retorts; in so far as they are of kinds occurring in more than one kind of furnace",
        "F28": "HEAT EXCHANGE IN GENERAL",
        "F28B": "Steam or vapour condensers",
        "F28C": "Heat-exchange apparatus; not provided for in another subclass; in which the heat-exchange media come into direct contact without chemical interaction",
        "F28D": "Heat-exchange apparatus; not provided for in another subclass; in which the heat-exchange media do not come into direct contact; Heat storage plants or apparatus in general",
        "F28F": "Details of heat-exchange or heat-transfer apparatus; of general application",
        "F28G": "Cleaning of internal or external surfaces of heatexchange or heat-transfer conduits; e.g. water tubes of boilers",
        "F41": "WEAPONS",
        "F41A": "Functional features or details common to both smallarms and ordnance; e.g. cannons; Mountings for smallarms or ordnance",
        "F41B": "Weapons for projecting missiles without use of explosive or combustible propellant charge; Weapons not otherwise provided for",
        "F41C": "Smallarms; e.g. pistols; rifles; Accessories therefor",
        "F41F": "Apparatus for launching projectiles or missiles from barrels; e.g. cannons; Launchers for rockets or torpedoes; Harpoon guns",
        "F41G": "Weapon sights; Aiming",
        "F41H": "Armour; Armoured turrets; Armoured or armed vehicles; Means of attack or defence; e.g. camouflage; in general",
        "F41J": "Targets; Target ranges; Bullet catchers",
        "F42": "AMMUNITION; BLASTING",
        "F42B": "Explosive charges; e.g. for blasting; Fireworks; Ammunition",
        "F42C": "Ammunition fuzes; Arming or safety means therefor",
        "F42D": "Blasting",
        "G01": "MEASURING; TESTING",
        "G01B": "Measuring length; thickness; or similar linear dimensions; Measuring angles; Measuring areas; Measuring irregularities of surfaces or contours",
        "G01C": "Measuring distances; levels; or bearings; Surveying; Navigation; Gyroscopic instruments; Photogrammetry",
        "G01D": "Measuring not specially adapted for a specific variable; Arrangements for measuring two or more variables not covered by a single other subclass; Tariff metering apparatus; Measuring or testing not otherwise provided for",
        "G01F": "Measuring volume; volume flow; mass flow; or liquid level; Metering by volume",
        "G01G": "Weighing",
        "G01H": "Measurement of mechanical vibrations or ultrasonic; sonic or infrasonic waves",
        "G01J": "Measurement of intensity; velocity; spectral content; polarisation; phase or pulse characteristics of infra-red; visible or ultra-violet light; Colorimetry; Radiation pyrometry",
        "G01K": "Measuring temperature; Measuring quantity of heat; Thermally-sensitive elements not otherwise provided for",
        "G01L": "Measuring force; stress; torque; work; mechanical power; mechanical efficiency; or fluid pressure",
        "G01M": "Testing static or dynamic balance of machines or structures; Testing structures or apparatus not otherwise provided for",
        "G01N": "Investigating or analysing materials by determining their chemical or physical properties",
        "G01P": "Measuring linear or angular speed; acceleration; deceleration; or shock; Indicating presence; absence; or direction; of movement",
        "G01R": "Measuring electric variables; Measuring magnetic variables following the title of class G 01; measuring diffusion of ions in an electric field; e.g. electrophoresis; electro-osmosis; G 01 N; investigating non-electric or non-magnetic properties of materials by using electric or magnetic methods G 01 N; indicating correct tuning of resonant circuits H 03 J 3/12; monitoring electronic pulse counters H 03 K21/40; monitoring operation of communication systems H 04)",
        "G01S": "Radio direction-finding; Radio navigation; Determining distance or velocity by use of radio waves; Locating or presence-detecting by use of the reflection or reradiation of radio waves; Analogous arrangements using other waves",
        "G01T": "Measurement of nuclear or X-radiation",
        "G01V": "Geophysics; Gravitational measurements; Detecting masses or objects; Tags",
        "G01W": "Meteorology",
        "G02": "OPTICS",
        "G02B": "Optical elements; systems; or apparatus",
        "G02C": "Spectacles; Sunglasses or goggles insofar as they have the same features as spectacles",
        "G02F": "Devices or arrangements; the optical operation of which is modified by changing the optical properties of the medium of the devices or arrangements for the control of the intensity; colour; phase; polarisation or direction of light; e.g. switching; gating; modulating or demodulating; Techniques or procedures for the operation thereof; Frequency-changing; Nonlinear optics; Optical logic elements; Optical analogue/digital converters",
        "G03": "PHOTOGRAPHY; CINEMATOGRAPHY; ANALOGOUS TECHNIQUES USINGWAVES OTHER THAN OPTICALWAVES; ELECTROGRAPHY; HOLOGRAPHY",
        "G03B": "Apparatus or arrangements for taking photographs or for projecting or viewing them; Apparatus or arrangements employing analogous techniques using waves other than optical waves; Accessories therefor",
        "G03C": "Photosensitive materials for photographic purposes; Photographic processes; e.g. cine; X-ray; colour; stereo-photographic processes; Auxiliary processes in photography",
        "G03D": "Apparatus for processing exposed photographic materials; Accessories therefor",
        "G03F": "Photomechanical production of textured or patterned surfaces; e.g. for printing; for processing of semiconductor devices; Materials therefor; Originals therefor; Apparatus specially adapted therefor",
        "G03G": "Electrography; Electrophotography; Magnetography",
        "G03H": "Holographic processes or apparatus",
        "G04": "HOROLOGY",
        "G04B": "Mechanically-driven clocks or watches; Mechanical parts of clocks or watches in general; Time-pieces using the position of the sun; moon; or stars",
        "G04C": "Electromechanical clocks or watches",
        "G04D": "Apparatus or tools specially designed for making or maintaining clocks or watches",
        "G04F": "Time-interval measuring",
        "G04G": "Electronic time-pieces",
        "G05": "CONTROLLING; REGULATING",
        "G05B": "Control or regulating systems in general; Functional elements of such systems; Monitoring or testing arrangements for such systems or elements",
        "G05D": "Systems for controlling or regulating non-electric variables",
        "G05F": "Systems for regulating electric or magnetic variables",
        "G05G": "Control devices or systems insofar as characterised by mechanical features only",
        "G06": "COMPUTING; CALCULATING; COUNTING",
        "G06C": "Digital computers in which all the computation is effected mechanically",
        "G06D": "Digital fluid-pressure computing devices",
        "G06E": "Optical computing devices",
        "G06F": "Electric digital data processing",
        "G06G": "Analogue computers",
        "G06J": "Hybrid computing arrangements",
        "G06K": "Recognition of data; Presentation of data; Record carriers; Handling record carriers",
        "G06": "Counting mechanisms; Counting of objects not otherwise provided for",
        "G06N": "Computer systems based on specific computational models",
        "G06T": "Image data processing or generation; in general",
        "G07": "CHECKING-DEVICES",
        "G07B": "Ticket-issuing apparatus; Fare-registering apparatus; Franking apparatus",
        "G07C": "Time or attendance registers; Registering or indicating the working of machines; Generating random numbers; Voting or lottery apparatus; Arrangements; systems; or apparatus for checking not provided for elsewhere",
        "G07D": "Sorting; testing; changing; delivering; or otherwise handling coins; Testing or changing paper currency; Testing securities; bonds; or similar valuable papers",
        "G07F": "Coin-freed or like apparatus",
        "G07G": "Registering the receipt of cash; valuables; or tokens",
        "G08": "SIGNALLING",
        "G08B": "Signalling or calling systems; Order telegraphs; Alarm systems",
        "G08C": "Transmission systems for measured values; control or similar signals",
        "G08G": "Traffic control systems",
        "G09": "EDUCATING; CRYPTOGRAPHY; DISPLAY; ADVERTISING; SEALS",
        "G09B": "Educational or demonstration appliances; Appliances for teaching; or communicating with; the blind; deaf or mute; Models; Planetaria; Globes; Maps; Diagrams",
        "G09C": "Ciphering or deciphering apparatus for cryptographic or other purposes involving the need for secrecy",
        "G09D": "Railway or like time or fare tables; Perpetual calendars",
        "G09F": "Displaying; Advertising; Signs; Labels or nameplates; Seals",
        "G09G": "Arrangements or circuits for control of indicating devices using static means to present variable information",
        "G10": "MUSICAL INSTRUMENTS; ACOUSTICS",
        "G10B": "Organs; Harmoniums",
        "G10C": "Pianos",
        "G10D": "Musical instruments not otherwise provided for",
        "G10F": "Automatic musical instruments",
        "G10G": "Aids for music",
        "G10H": "Electrophonic musical instruments",
        "G10K": "Sound-producing devices; Acoustics not otherwise provided for",
        "G10L": "Speech analysis or synthesis; Speech recognition",
        "G11": "INFORMATION STORAGE",
        "G11B": "Information storage based on relative movement between record carrier and transducer",
        "G11C": "Static stores",
        "G12": "INSTRUMENT DETAILS",
        "G12B": "Details of instruments; or comparable details of other apparatus; not otherwise provided for",
        "G21": "NUCLEAR PHYSICS; NUCLEAR ENGINEERING",
        "G21B": "Fusion reactors",
        "G21C": "Nuclear reactors",
        "G21D": "Nuclear power plant",
        "G21F": "Protection against X-radiation; gamma radiation; corpuscular radiation; or particle bombardment; Treating radioactively contaminated material; Decontamination arrangements therefor",
        "G21G": "Conversion of chemical elements; Radioactive sources",
        "G21H": "Obtaining energy from radioactive sources; Applications of radiation from radioactive sources; Utilising cosmic radiation",
        "G21J": "Nuclear explosives; Applications thereof",
        "G21K": "Techniques for handling particles or electromagnetic radiation not otherwise provided for; Irradiation devices; Gamma- or X-ray microscopes",
        "H01": "BASIC ELECTRIC ELEMENTS",
        "H01B": "Cables; Conductors; Insulators; Selection of materials for their conductive; insulating; or dielectric properties",
        "H01C": "Resistors",
        "H01F": "Magnets; Inductances; Transformers; Selection of materials for their magnetic properties",
        "H01G": "Capacitors; Capacitors; rectifiers; detectors; switching devices; light-sensitive or temperaturesensitive devices of the electrolytic type",
        "H01H": "Electric switches; Relays; Selectors; Emergency protective devices",
        "H01J": "Electric discharge tubes or discharge lamps",
        "H01K": "Electric incandescent lamps",
        "H01L": "Semiconductor devices; Electric solid state devices not otherwise provided for",
        "H01M": "Processes or means; e.g. batteries; for the direct conversion of chemical energy into electrical energy",
        "H01P": "Waveguides; Resonators; lines; or other devices of the waveguide type",
        "H01Q": "Aerials",
        "H01R": "Electrically-conductive connections; Structural associations of a plurality of mutually-insulated electrical connecting elements; Coupling devices; Current collectors",
        "H01S": "Devices using stimulated emission",
        "H01T": "Spark gaps; Overvoltage arresters using spark gaps; Sparking plugs; Corona devices; Generating ions to be introduced into non-enclosed gases",
        "H02": "GENERATION; CONVERSION; OR DISTRIBUTION OF ELECTRIC POWER",
        "H02B": "Boards; substations; or switching arrangements for the supply or distribution of electric power",
        "H02G": "Installation of electric cables or lines; or of combined optical and electric cables or lines",
        "H02H": "Emergency protective circuit arrangements",
        "H02J": "Circuit arrangements or systems for supplying or distributing electric power; Systems for storing electric energy",
        "H02K": "Dynamo-electric machines",
        "H02M": "Apparatus for conversion between ac and ac; between ac and dc; or between dc and dc; and for use with mains or similar power supply systems; Conversion of dc or ac input power into surge output power; Control or regulation thereof",
        "H02N": "Electric machines not otherwise provided for",
        "H02P": "Control or regulation of electric motors; generators; or dynamo-electric converters; Controlling transformers; reactors or choke coils",
        "H03": "BASIC ELECTRONIC CIRCUITRY",
        "H03B": "Generation of oscillations; directly or by frequency-changing; by circuits employing active elements which operate in a non-switching manner; Generation of noise by such circuits",
        "H03C": "Modulation",
        "H03D": "Demodulation or transference of modulation from one carrier to another",
        "H03F": "Amplifiers",
        "H03G": "Control of amplification",
        "H03H": "Impedance networks; e.g. resonant circuits; Resonators",
        "H03J": "Tuning resonant circuits; Selecting resonant circuits",
        "H03K": "Pulse technique",
        "H03L": "Automatic control; starting; synchronisation; or stabilisation of generators of electronic oscillations or pulses",
        "H03M": "Coding; decoding or code conversion; in general",
        "H04": "ELECTRIC COMMUNICATION TECHNIQUE",
        "H04B": "Transmission",
        "H04H": "Broadcast communication",
        "H04J": "Multiplex communication",
        "H04K": "Secret communication; Jamming of communication",
        "H04L": "Transmission of digital information; e.g. telegraphic communication",
        "H04M": "Telephonic communication",
        "H04N": "Pictorial communication; e.g. television",
        "H04Q": "Selecting",
        "H04R": "Loudspeakers; microphones; gramophone pick-ups or like acoustic electromechanical transducers; Deaf-aid sets; Public address systems",
        "H04S": "Stereophonic systems",
        "H05": "ELECTRIC TECHNIQUES NOT OTHERWISE PROVIDED FOR",
        "H05B": "Electric heating; Electric lighting not otherwise provided for",
        "H05C": "Electric circuits or apparatus specially designed for use in equipment for killing; stunning; enclosing or guiding living beings",
        "H05F": "Static electricity; Naturally-occurring electricity",
        "H05G": "X-ray technique",
        "H05H": "Plasma technique; Production of accelerated electrically- charged particles or of neutrons; Production or acceleration of neutral molecular or atomic beams"
    }
    
    def get_patent_content(self, patent_code):
        self.patent_code = patent_code
        if len(patent_code)== 0:
            return False
        else:
            return self.patents[patent_code]
